# Generated by Django 5.0.7 on 2024-07-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpanel', '0002_alter_product_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
